module Alba
  # Represents attribute with `if` option
  class ConditionalAttribute
    @body: Symbol | Proc | Alba::Association | Alba::TypedAttribute | Alba::NestedAttribute
    @condition: Symbol | Proc

    def initialize: (
      body: Symbol | Proc | Alba::Association | Alba::TypedAttribute | Alba::NestedAttribute,
      condition: Symbol | Proc
    ) -> void

    def with_passing_condition: (
      resource: Alba::Resource,
      ?object: untyped
    ) { (Symbol | Proc | Alba::Association | Alba::TypedAttribute | Alba::NestedAttribute) -> untyped } -> untyped

    private

    def condition_passes?: (Alba::Resource resource, untyped object) -> bool
    def with_two_arity_proc_condition?: () -> bool
    def second_object: (untyped object, Alba::Resource resource) -> untyped
  end
end
