module Alba
  # Represents attribute with `if` option
  class ConditionalAttribute
    type condition = Symbol | Proc
    @body: untyped
    @condition: untyped

    def initialize: (
      body: Alba::Resource::attribute,
      condition: condition
    ) -> void

    def with_passing_condition: (
      resource: untyped,
      ?object: untyped
    ) { (Alba::Resource::attribute) -> untyped } -> untyped

    private

    def condition_passes?: (untyped resource, untyped object) -> bool
    def with_two_arity_proc_condition?: () -> bool
    def second_object: (untyped object, untyped resource) -> untyped
  end
end
