module Alba
  # Module for printing deprecation warning
  module Deprecation
    def self?.warn: (_ToS message) -> nil
    def caller_locations: (Range[Integer]) -> Array[Thread::Backtrace::Location]
  end
end
