module Alba
  # Representing nested attribute
  class NestedAttribute
    attr_writer key_transformation: Alba::transform_type

    @key_transformation: Alba::transform_type
    @block: Proc

    def initialize: (
      ?key_transformation: Alba::transform_type
    ) { () -> void } -> void

    def value: (
      object: untyped,
      params: generic_hash,
      within: within,
      ?select: Method?
    ) -> generic_hash
  end
end
