module Alba
  module Resource
    type attribute = untyped

    INTERNAL_VARIABLES: Hash[Symbol, untyped]
    WITHIN_DEFAULT: Object
    EMPTY_HASH: generic_hash

    def self.included: (Class) -> untyped

    module InstanceMethods
      @object: untyped
      @params: generic_hash
      @within: untyped

      attr_reader object: untyped
      attr_reader params: generic_hash

      def initialize: (untyped, ?params: generic_hash, ?within: untyped, ?select: Method?) -> void
      def serialize: (?root_key: root_key_type, ?meta: generic_hash) -> String
      def to_json: (?generic_hash, ?root_key: root_key_type, ?meta: generic_hash) -> String
      def as_json: (?generic_hash, ?root_key: root_key_type, ?meta: generic_hash) -> untyped
      def serializable_hash: () -> untyped
      alias to_h serializable_hash

      def deprecated_serializable_hash: () -> untyped
      def serialize_with: (untyped) -> String
      def hash_with_metadata: (untyped, generic_hash) -> untyped
      def _metadata: (untyped, generic_hash) -> generic_hash
      def serializable_hash_for_collection: () -> untyped
      def deprecated_serializable_hash_for_collection: () -> untyped
      def fetch_key: () -> root_key_type
      def _key_for_collection: () -> root_key_type
      def _key: () -> root_key_type
      def resource_name: (?pluralized: bool) -> String
      def transforming_root_key?: () -> bool
      def converter: () -> Proc
      def collection_converter: () -> Proc
      def attributes_to_hash: (untyped, generic_hash) -> generic_hash
      def attributes: () -> Hash[Symbol | String, attribute]
      def select: (untyped, untyped, untyped) -> bool
      def set_key_and_attribute_body_from: (untyped, untyped, attribute, generic_hash) -> untyped
      def do_select: (untyped, untyped, untyped) -> bool
      def handle_error: (StandardError, untyped, Symbol | String, attribute, generic_hash) -> untyped
      def transform_key: (untyped) -> untyped
      def fetch_attribute: (untyped, untyped, attribute) -> untyped
      def fetch_attribute_from_object_and_resource: (untyped, Symbol) -> untyped
      def _fetch_attribute_from_object_first: (untyped, Symbol) -> untyped
      def _fetch_attribute_from_resource_first: (untyped, Symbol) -> untyped
      def nil_handler: () -> untyped
      def yield_if_within: (Symbol) { (untyped) -> untyped } -> untyped
      def check_within: (Symbol) -> untyped
      def _setup: () -> void

      # These methods are available on the eventual resource instance. Declaring
      # them here models the module's inclusion context for Steep.
      def class: () -> Class
      def instance_eval: [A] () { () [self: self] -> A } -> A
      def instance_exec: [A] (*untyped) { (*untyped) [self: self] -> A } -> A
      def __send__: (Symbol, *untyped) -> untyped
      def binding: () -> Binding
      def encode: (untyped) -> String
    end

    interface _ClassContext
      def alias_method: (Symbol, Symbol) -> Symbol
      def private: (*Symbol) -> untyped
      def instance_method: (Symbol) -> UnboundMethod
      def include: (*Module) -> untyped
      def extend: (*Module) -> untyped
      def class_eval: [A] () { () [self: untyped] -> A } -> A
      def module_eval: [A] () { () [self: untyped] -> A } -> A
      def name: () -> untyped
      def dup: () -> untyped
      def new: (*untyped, **untyped) -> untyped
      def _resource_methods: () -> Array[Symbol]
    end

    module ClassMethods
      @_attributes: Hash[Symbol | String, attribute]
      @_key: class_key_type
      @_key_for_collection: class_key_type
      @_meta: untyped
      @_transform_type: transform_type
      @_transforming_root_key: bool
      @_key_transformation_cascade: bool
      @_on_error: untyped
      @_on_nil: untyped
      @_layout: Layout?
      @_collection_key: key_type
      @_helper: Module?
      @_resource_methods: Array[Symbol]
      @_select_arity: Integer?
      @_traits: Hash[Symbol, Proc]
      @_classes_with_traits: Hash[Array[Symbol], untyped]?

      def alias_method: (Symbol, Symbol) -> Symbol
      def private: (*Symbol) -> untyped
      def instance_method: (Symbol) -> UnboundMethod
      def include: (*Module) -> untyped
      def extend: (*Module) -> untyped
      def class_eval: [A] () { () [self: untyped] -> A } -> A
      def module_eval: [A] () { () [self: untyped] -> A } -> A
      def name: () -> untyped
      def dup: () -> untyped
      def new: (untyped, ?with_traits: Symbol | Array[Symbol] | nil, **untyped) -> untyped
      private def class_with_traits: (untyped) -> untyped
      private def build_class_with_traits: (untyped) -> untyped
      def itself: () -> Class
      def _resource_methods: () -> Array[Symbol]

      def method_added: (Symbol) -> untyped
      def inherited: (Class) -> untyped
      def attributes: (*(Symbol | String), ?if: Proc | Symbol | nil, **untyped) -> untyped
      def assign_attributes: (Array[Symbol | String], Proc | Symbol | nil) -> untyped
      def assign_attributes_with_types: (Hash[Symbol | String, untyped], Proc | Symbol | nil) ?{ (untyped) -> untyped } -> untyped
      def attribute: (?Symbol | String | nil, ?if: Proc | Symbol | nil, **untyped) ?{ (untyped) -> untyped } -> untyped
      def association: (Symbol | String, ?Proc?, ?resource: untyped, ?serializer: untyped, ?source: Proc?, ?key: key_type, ?with_traits: Symbol | Array[Symbol] | nil, ?params: generic_hash, **untyped) ?{ () -> void } -> untyped
      alias one association
      alias many association
      alias has_one association
      alias has_many association
      def nesting: () -> String?
      def nested_attribute: (Symbol | String, **untyped) ?{ () -> void } -> untyped
      alias nested nested_attribute
      def trait: (Symbol | String) ?{ () -> void } -> untyped
      def root_key: (Symbol | String, ?Symbol | String | nil) -> untyped
      def root_key_for_collection: (Symbol | String) -> untyped
      def root_key!: () -> untyped
      def meta: (?Symbol) ?{ () -> generic_hash } -> untyped
      def layout: (?file: String?, ?inline: Proc?) -> untyped
      def transform_keys: (Symbol | String, ?root: bool, ?cascade: bool) -> untyped
      def transform_keys!: (Symbol | String) -> untyped
      def collection_key: (Symbol | String) -> untyped
      def on_error: (?Symbol?) ?{ (*untyped) -> untyped } -> untyped
      def validated_error_handler: (untyped) -> Symbol
      def on_nil: () ?{ (*untyped) -> untyped } -> untyped
      def helper: (?Module) ?{ (*untyped) -> untyped } -> untyped
      def prefer_resource_method!: () -> untyped
      def prefer_object_method!: () -> untyped
    end

    include InstanceMethods
    extend ClassMethods
  end

  Serializer: singleton(Resource)
end
