# frozen_string_literal: true

D = Steep::Diagnostic

Dir.glob(File.join(__dir__, '*.rb')).each do |path|
  example_name = File.basename(path, '.rb')

  target :"example_#{example_name}" do
    signature '../sig', 'sig/examples.rbs'

    check File.basename(path)

    library 'json'
    library 'logger'
    library 'pathname'

    configure_code_diagnostics(D::Ruby.strict)
  end
end
