name: Dummy Rails app tests

on: [push,pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.1]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: false
    - name: Run dummy Rails app tests
      working-directory: ./test/dummy/rails
      run: |
        bundle exec rake
