name: Performance Check

on: [pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, 3.0, 3.1]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: false
    - name: Run benchmark
      run: |
        ruby script/perf_check.rb
